# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSystemInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='parkingslotStatus',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='userPaymentStatus',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
