# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSystemInfo', '0002_auto_20170509_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='parkingslotID',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
