# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSystemInfo', '0003_auto_20170511_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='parkingslotCode',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='parkingslotID',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='parkingslotStatus',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='userCode',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='userPaymentStatus',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
