# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverSystemInfo', '0004_auto_20170511_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systeminfo',
            name='userID',
        ),
    ]
