# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverSystemInfo', '0005_remove_systeminfo_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='userName',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
