# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPaymentStatus',
            field=models.CharField(default='unpaid', max_length=200),
        ),
    ]
