# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_auto_20170509_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userCodeVerStatus',
            field=models.CharField(default='unmatch', max_length=200),
        ),
    ]
