# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_user_usercodeverstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userCodeVerStatus',
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPaymentStatus',
            field=models.IntegerField(default=0),
        ),
    ]
