# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0004_auto_20170511_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userCode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='paystatus',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userPassword',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPaymentStatus',
        ),
    ]
